package;

class Input {
  
  public static var KEY_STRINGS:Map<Int, String> = [
    8 => "backspace",
    9 => "tab",
    13 => "enter",
    16 => "shift",
    17 => "ctrl",
    18 => "alt",
    19 => "pause/break",
    20 => "caps lock",
    27 => "escape",
    32 => "(space)",
    33 => "page up",
    34 => "page down",
    35 => "end",
    36 => "home",
    37 => "left arrow",
    38 => "up arrow",
    39 => "right arrow",
    40 => "down arrow",
    45 => "insert",
    46 => "delete",
    48 => "0",
    49 => "1",
    50 => "2",
    51 => "3",
    52 => "4",
    53 => "5",
    54 => "6",
    55 => "7",
    56 => "8",
    57 => "9",
    65 => "a",
    66 => "b",
    67 => "c",
    68 => "d",
    69 => "e",
    70 => "f",
    71 => "g",
    72 => "h",
    73 => "i",
    74 => "j",
    75 => "k",
    76 => "l",
    77 => "m",
    78 => "n",
    79 => "o",
    80 => "p",
    81 => "q",
    82 => "r",
    83 => "s",
    84 => "t",
    85 => "u",
    86 => "v",
    87 => "w",
    88 => "x",
    89 => "y",
    90 => "z",
    91 => "left window key",
    92 => "right window key",
    93 => "select key",
    96 => "numpad 0",
    97 => "numpad 1",
    98 => "numpad 2",
    99 => "numpad 3",
    100 => "numpad 4",
    101 => "numpad 5",
    102 => "numpad 6",
    103 => "numpad 7",
    104 => "numpad 8",
    105 => "numpad 9",
    106 => "multiply",
    107 => "add",
    109 => "subtract",
    110 => "decimal point",
    111 => "divide",
    112 => "f1",
    113 => "f2",
    114 => "f3",
    115 => "f4",
    116 => "f5",
    117 => "f6",
    118 => "f7",
    119 => "f8",
    120 => "f9",
    121 => "f10",
    122 => "f11",
    123 => "f12",
    144 => "num lock",
    145 => "scroll lock",
    186 => "semi-colon",
    187 => "equal sign",
    188 => "comma",
    189 => "dash",
    190 => "period",
    191 => "forward slash",
    192 => "grave accent",
    219 => "open bracket",
    220 => "back slash",
    221 => "close braket",
    222 => "single quote"
  ];
  
  public static inline var KEY_BACKSPACE = 8;
  public static inline var KEY_TAB = 9;
  public static inline var KEY_ENTER = 13;
  public static inline var KEY_SHIFT = 16;
  public static inline var KEY_CTRL = 17;
  public static inline var KEY_ALT = 18;
  public static inline var KEY_PAUSE_BREAK = 19;
  public static inline var KEY_CAPS_LOCK = 20;
  public static inline var KEY_ESCAPE = 27;
  public static inline var KEY_SPACE = 32;
  public static inline var KEY_PAGE_UP = 33;
  public static inline var KEY_PAGE_DOWN = 34;
  public static inline var KEY_END = 35;
  public static inline var KEY_HOME = 36;
  public static inline var KEY_LEFT_ARROW = 37;
  public static inline var KEY_UP_ARROW = 38;
  public static inline var KEY_RIGHT_ARROW = 39;
  public static inline var KEY_DOWN_ARROW = 40;
  public static inline var KEY_INSERT = 45;
  public static inline var KEY_DELETE = 46;
  public static inline var KEY_0 = 48;
  public static inline var KEY_1 = 49;
  public static inline var KEY_2 = 50;
  public static inline var KEY_3 = 51;
  public static inline var KEY_4 = 52;
  public static inline var KEY_5 = 53;
  public static inline var KEY_6 = 54;
  public static inline var KEY_7 = 55;
  public static inline var KEY_8 = 56;
  public static inline var KEY_9 = 57;
  public static inline var KEY_A = 65;
  public static inline var KEY_B = 66;
  public static inline var KEY_C = 67;
  public static inline var KEY_D = 68;
  public static inline var KEY_E = 69;
  public static inline var KEY_F = 70;
  public static inline var KEY_G = 71;
  public static inline var KEY_H = 72;
  public static inline var KEY_I = 73;
  public static inline var KEY_J = 74;
  public static inline var KEY_K = 75;
  public static inline var KEY_L = 76;
  public static inline var KEY_M = 77;
  public static inline var KEY_N = 78;
  public static inline var KEY_O = 79;
  public static inline var KEY_P = 80;
  public static inline var KEY_Q = 81;
  public static inline var KEY_R = 82;
  public static inline var KEY_S = 83;
  public static inline var KEY_T = 84;
  public static inline var KEY_U = 85;
  public static inline var KEY_V = 86;
  public static inline var KEY_W = 87;
  public static inline var KEY_X = 88;
  public static inline var KEY_Y = 89;
  public static inline var KEY_Z = 90;
  public static inline var KEY_LEFT_WINDOW_KEY = 91;
  public static inline var KEY_RIGHT_WINDOW_KEY = 92;
  public static inline var KEY_SELECT_KEY = 93;
  public static inline var KEY_NUMPAD_0 = 96;
  public static inline var KEY_NUMPAD_1 = 97;
  public static inline var KEY_NUMPAD_2 = 98;
  public static inline var KEY_NUMPAD_3 = 99;
  public static inline var KEY_NUMPAD_4 = 100;
  public static inline var KEY_NUMPAD_5 = 101;
  public static inline var KEY_NUMPAD_6 = 102;
  public static inline var KEY_NUMPAD_7 = 103;
  public static inline var KEY_NUMPAD_8 = 104;
  public static inline var KEY_NUMPAD_9 = 105;
  public static inline var KEY_MULTIPLY = 106;
  public static inline var KEY_ADD = 107;
  public static inline var KEY_SUBTRACT = 109;
  public static inline var KEY_DECIMAL_POINT = 110;
  public static inline var KEY_DIVIDE = 111;
  public static inline var KEY_F1 = 112;
  public static inline var KEY_F2 = 113;
  public static inline var KEY_F3 = 114;
  public static inline var KEY_F4 = 115;
  public static inline var KEY_F5 = 116;
  public static inline var KEY_F6 = 117;
  public static inline var KEY_F7 = 118;
  public static inline var KEY_F8 = 119;
  public static inline var KEY_F9 = 120;
  public static inline var KEY_F10 = 121;
  public static inline var KEY_F11 = 122;
  public static inline var KEY_F12 = 123;
  public static inline var KEY_NUM_LOCK = 144;
  public static inline var KEY_SCROLL_LOCK = 145;
  public static inline var KEY_SEMI_COLON = 186;
  public static inline var KEY_EQUAL_SIGN = 187;
  public static inline var KEY_COMMA = 188;
  public static inline var KEY_DASH = 189;
  public static inline var KEY_PERIOD = 190;
  public static inline var KEY_FORWARD_SLASH = 191;
  public static inline var KEY_GRAVE_ACCENT = 192;
  public static inline var KEY_OPEN_BRACKET = 219;
  public static inline var KEY_BACK_SLASH = 220;
  public static inline var KEY_CLOSE_BRAKET = 221;
  public static inline var KEY_SINGLE_QUOTE = 222;
  
  public static var keyBindings:Map<String, Int> = [
    "accelerate" => KEY_W,
    "brake" => KEY_S,
    "gear_plus" => KEY_Q,
    "gear_minus" => KEY_Z
  ];

  public function new() {}
}
